version: "3.9"

services:
  obdm-middleware:
    build: .
    container_name: obdm-middleware
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      JWT_SECRET_KEY: super-secret-key
